#!/bin/bash

source "$(git --exec-path)/git-sh-setup"

`dirname $0`/git-fetch-upstream

git pull
git remote prune origin

# Remove all branches that has been deleted upstream.
git branch -vv  | grep ": gone" | awk '{print $3}' |  sed -e "s/[^\/]*\///" -e "s/://"  | xargs -n 1 -I {} git branch -D {}
