#!/bin/sh

source "$(git --exec-path)/git-sh-setup"

git pull
git remote prune origin

# Remove all branches that has been deleted upstream.
git branch -vv  | grep ": gone" | awk '{print $3}' |  sed -e "s/[^\/]*\///" -e "s/://" | xargs git branch -D
